dist: focal    # Ubuntu 20.04 LTS
language: ruby
gemfile: Gemfile

addons:
  apt:
    update: true
    packages:
    - libgnutls28-dev
    - libbotan-2-dev
    - libmbedtls-dev
    - libboost-program-options-dev
    - botan

jdk:
  - openjdk16

before_install: 
  - git clone https://github.com/MestreLion/git-tools # Distro version is currently broken
  - ./git-tools/git-restore-mtime
  - rm -rf ./git-tools

install:
  - make install

script:
  - make test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache:
  bundler: true               # Enable caching of bundler gem packages
  directories:
  - $TRAVIS_BUILD_DIR/.cache  # Enable caching link checks
  - $TRAVIS_BUILD_DIR/validation/certs/build # Enable caching of generated certificates
  - $TRAVIS_BUILD_DIR/validation/certs/results/vresults # Enable caching of chain validation results

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  target_branch: gh-pages
  keep_history: false
  verbose: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
