dist: jammy    # Ubuntu 22.04 LTS
language: ruby
gemfile: Gemfile

# Clone full git history for git-restore-mtime to work
git:
  depth: false

addons:
  apt:
    update: true
    packages:
    - libgnutls28-dev
    - libbotan-2-dev
    - libmbedtls-dev
    - botan
    - python3-pip

jdk:
  - openjdk17

# Restore file times for better GNU Make optimizations
before_install: 
  - git clone https://github.com/MestreLion/git-tools # Distro version is currently broken
  - ./git-tools/git-restore-mtime
  - rm -rf ./git-tools

install:
  - make install

script:
  - make test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache:
  bundler: true               # Enable caching of bundler gem packages
  directories:
  - $TRAVIS_BUILD_DIR/.cache  # Enable caching link checks
  - $TRAVIS_BUILD_DIR/validation/certs/build # Enable caching of generated certificates
  - $TRAVIS_BUILD_DIR/validation/certs/results/vresults # Enable caching of chain validation results

before_deploy: 
  - wget -q --output-document=firebase https://firebase.tools/bin/linux/latest
  - chmod +x firebase

deploy:
  # Firebase production deployment
  - provider: script # uses FIREBASE_TOKEN
    on:
      branch: master
    skip_cleanup: true
    script: make deploy-production
  # Firebase preview deployment
  - provider: script # uses FIREBASE_TOKEN
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = preview-*
    skip_cleanup: true
    script: make deploy-preview
