dist: bionic    # Ubuntu 18.04 LTS
language: ruby
gemfile: Gemfile

before_install: 
  - sudo apt update
  - sudo apt install -y gnutls-bin
  - sudo apt install python3
  - sudo apt install -y python-pip && pip install shyaml
  - git clone https://github.com/MestreLion/git-tools # Distro version is currently broken

script: 
  - ./git-tools/git-restore-mtime
  - make test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache:
  bundler: true               # Enable caching of bundler gem packages
  directories:
  - $TRAVIS_BUILD_DIR/.cache  # Enable caching link checks
  - $TRAVIS_BUILD_DIR/_certs  # Enable caching of generated certificates
  - $TRAVIS_BUILD_DIR/_errors # Enable caching of generated error metadata
  - $TRAVIS_BUILD_DIR/assets/certs # Enable caching of generated certificates

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  target_branch: gh-pages
  keep_history: false
  verbose: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
