# Site settings
title: Usable X.509 errors
description: Let's make the validation of TLS certificates usable.
author: Centre for Research on Cryptography and Security, Masaryk University, Czechia
url: https://x509errors.cz
repo-url: https://github.com/crocs-muni/usable-cert-validation
email: webmaster@x509errors.org

# Build settings
include: [ ".well-known" ]
exclude: [ "Gemfile", "Gemfile.lock", "Makefile", "requirements.txt"    # Build settings
         , "README.md", "LICENSE.md", "CODE_OF_CONDUCT.md"              # Development documentation
         , "utils/", "validation/"                                      # Development files
         ]

collections:
  pages:
    output: true
    permalink: /:title
  guides:
    output: true
    permalink: /guides/:title

sass:
  sass_dir: assets/css
cache_dir: .cache

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:              "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  css_hash:         "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
  js:               "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  js_hash:          "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
  jquery:           "https://code.jquery.com/jquery-3.2.1.slim.min.js"
  jquery_hash:      "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  popper_hash:      "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"

target-blank:
  add_css_classes: ext-link

plugins:
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
