# Site settings
title: Usable X.509 errors
description: Let's make the validation of TLS certificates usable.
author: Centre for Research on Cryptography and Security, Masaryk University, Czechia
url: https://x509errors.org
repo-url: https://github.com/crocs-muni/usable-cert-validation
email: webmaster@x509errors.org

# Build settings
include: [ ".well-known" ]
exclude: [ "Gemfile", "Gemfile.lock", "Makefile", "requirements.txt"    # Build settings
         , "README.md", "LICENSE.md", "CODE_OF_CONDUCT.md"              # Development documentation
         , "utils/", "validation/"                                      # Development files
         ]

collections:
  pages:
    output: true
    permalink: /:title
  guides:
    output: true
    permalink: /guides/:title

sass:
  sass_dir: assets/_scss
  style: compressed
cache_dir: .cache

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  bootstrap_css:      "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css"
  bootstrap_css_hash: "sha512-P5MgMn1jBN01asBgU0z60Qk4QxiXo86+wlFahKrsQf37c9cro517WzVSPPV1tDKzhku2iJ2FVgL67wG03SGnNA=="
  fonts:              "https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,700&display=swap&subset=latin-ext"
  fonts_hash:         "sha512-XIKPmR+Aa0qa2meabdUvYILIUtdOBdkO6kEsQmMytFHOtZKspAE3THShJWm7xkC9MpeTJgqezOdv+UltfV/EiQ=="
  jquery:             "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
  jquery_hash:        "sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
  bootstrap_js:       "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"
  bootstrap_js_hash:  "sha512-wV7Yj1alIZDqZFCUQJy85VN+qvEIly93fIQAN7iqDFCPEucLCeNFz4r35FCo9s6WrpdDQPi80xbljXB8Bjtvcg=="
  popper:             "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  popper_hash:        "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
  fa:                 "https://kit.fontawesome.com/036c3720fc.js"
  fa_hash:            "sha512-rtWWeIre4u08z776Ym06adY5CxapChGxl8H91d4e5weQc2eZmEazG4g8kytHD0eUTC3spBXOIU+PYGLHi8uVdw=="

target-blank:
  add_css_classes: ext-link

html-beautify:
  include:
    - "*.html"
    - "*.md"

plugins:
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
