servers:
  main: {}

verify:
  openssl:
    options: {}
    cli: openssl verify -CAfile root.pem -untrusted intermediate1.pem endpoint.pem
  gnutls:
    options: {}
  mbedtls:
    options: {}
  botan:
    options: {}
  openjdk:
    options: {}