servers:
  main: {}

verify:
  openssl:
    options:
      flags: "--allow_proxy"
    cli: openssl verify -CAfile root.pem -untrusted intermediate1.pem -untrusted intermediate2.pem -allow_proxy_certs endpoint.pem
  gnutls:
    options: {}
  mbedtls:
    options: {}
  botan:
    options: {}
  openjdk:
    options: {}