servers:
  main: {}

verify:
  openssl:
    options:
      purpose: SSL_SERVER
      trust_anchor: marked_root.pem
    cli: openssl verify -CAfile marked_root.pem -untrusted intermediate1.pem -purpose sslserver endpoint.pem