source 'https://rubygems.org'

gem 'jekyll'
gem 'html-proofer'

# The plugin in the gem repository is ccurrently not maintained.
# Temporarity provided locally.
# Local fix applied (URI escaping needed). Pull request submitted.
# gem 'jekyll-target-blank'
